# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{odiseo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{AP System}]
  s.date = %q{2011-06-06}
  s.description = %q{Adminsitracion de contabilidad}
  s.email = %q{info@ap-sys.com.ar}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/accounts_controller.rb",
    "app/controllers/entries_controller.rb",
    "app/controllers/exercises_controller.rb",
    "app/helpers/accounts_helper.rb",
    "app/helpers/entries_helper.rb",
    "app/helpers/exercises_helper.rb",
    "app/models/account.rb",
    "app/models/detail.rb",
    "app/models/entry.rb",
    "app/models/exercise.rb",
    "app/views/accounts/_account.html.haml",
    "app/views/accounts/_form.html.haml",
    "app/views/accounts/edit.html.haml",
    "app/views/accounts/index.html.haml",
    "app/views/accounts/list_account.html.haml",
    "app/views/accounts/new.html.haml",
    "app/views/accounts/print_movim.html.haml",
    "app/views/accounts/show.html.haml",
    "app/views/entries/_detail_fields.html.haml",
    "app/views/entries/_form.html.haml",
    "app/views/entries/edit.html.haml",
    "app/views/entries/index.html.haml",
    "app/views/entries/new.html.haml",
    "app/views/entries/show.html.haml",
    "app/views/exercises/_form.html.haml",
    "app/views/exercises/edit.html.haml",
    "app/views/exercises/index.html.haml",
    "app/views/exercises/new.html.haml",
    "app/views/exercises/show.html.haml",
    "config/routes.rb",
    "lib/odiseo.rb",
    "lib/odiseo/engine.rb",
    "odiseo.gemspec",
    "spec/odiseo_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/lguardiola/odiseo}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Proyecto Contable}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

